# Generated by Django 4.1.7 on 2023-04-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Birds',
            new_name='Bird',
        ),
    ]
