# Generated by Django 4.1.7 on 2023-04-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_feedings_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
